"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { isRichText, sanitizeRichText } from "@/lib/richText";
import AppModal from "@/components/ui/AppModal";
import AppButton from "@/components/ui/AppButton";
import EmptyState from "@/components/ui/EmptyState";

type ClientDocument = { id: string; title: string; category: string; version: number; content: string; accepted: boolean };
const category: Record<string, string> = { consent: "Zgoda", preparation: "Przygotowanie", aftercare: "Pielęgnacja", policy: "Regulamin", other: "Informacja" };

export default function ClientDocuments({ documents }: { documents: ClientDocument[] }) {
  const [selected, setSelected] = useState<ClientDocument | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const router = useRouter();
  async function accept() { if (!selected) return; setBusy(true); setError(""); try { const response = await fetch(`/api/client/documents/${selected.id}/accept`, { method: "POST" }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setSelected({ ...selected, accepted: true }); router.refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Nie udało się zapisać potwierdzenia."); } finally { setBusy(false); } }
  return <section id="dokumenty" className="scroll-mt-6 mt-14"><div className="flex items-end justify-between gap-4"><div><p className="text-[11px] tracking-[0.18em] text-ink-gold">DOKUMENTY</p><h2 className="mt-2 font-display text-3xl">Ważne informacje</h2></div><span className="text-xs text-ink-grey">{documents.filter((document) => !document.accepted).length} oczekuje</span></div>{documents.length === 0 ? <div className="mt-5"><EmptyState title="Wszystko przeczytane" description="Nie ma obecnie dokumentów wymagających Twojej uwagi." /></div> : <div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{documents.map((document) => <button type="button" key={document.id} onClick={() => { setError(""); setSelected(document); }} className="group min-h-40 border border-ink-white/15 bg-ink-charcoal/30 p-5 text-left transition-colors hover:border-ink-gold"><div className="flex items-start justify-between gap-3"><span className="text-3xl text-ink-gold">▤</span><span className={`border px-2 py-1 text-[10px] tracking-[0.08em] ${document.accepted ? "border-ink-gold/50 text-ink-gold" : "border-amber-400/50 text-amber-200"}`}>{document.accepted ? "POTWIERDZONE" : "DO PRZECZYTANIA"}</span></div><p className="mt-5 text-base text-ink-white">{document.title}</p><p className="mt-2 text-[11px] tracking-[0.1em] text-ink-grey">{category[document.category] ?? "DOKUMENT"} · WERSJA {document.version}</p></button>)}</div>}{selected && <AppModal title={selected.title} subtitle={`${category[selected.category] ?? "Dokument"} · wersja ${selected.version}`} size="lg" onClose={busy ? () => undefined : () => setSelected(null)} footer={<div className="flex justify-end gap-3">{selected.accepted ? <span className="py-2 text-xs tracking-[0.08em] text-ink-gold">✓ POTWIERDZONE</span> : <AppButton variant="primary" onClick={accept} disabled={busy}>{busy ? "ZAPIS…" : "PRZECZYTAŁEM(-AM) I AKCEPTUJĘ"}</AppButton>}</div>}><div className="max-h-[52vh] overflow-y-auto pr-2">{isRichText(selected.content) ? <div className="document-rich-text text-sm leading-relaxed text-ink-grey" dangerouslySetInnerHTML={{ __html: sanitizeRichText(selected.content) }} /> : <p className="whitespace-pre-line text-sm leading-relaxed text-ink-grey">{selected.content}</p>}</div>{error && <p role="alert" className="mt-4 text-sm text-red-300">{error}</p>}</AppModal>}</section>;
}
