"use client";

import Link from "next/link";
import { Bell, Mail } from "lucide-react";
import { useState } from "react";
import AppModal from "@/components/ui/AppModal";

type Message = { id: string; projectId: string; project: string; body: string; createdAt: string; unread: boolean };
type Notification = { id: string; title: string; body: string; href: string | null; createdAt: string; unread: boolean };
function Badge({ count }: { count: number }) { return count ? <span className="absolute -right-1 -top-1 min-w-4 rounded-full bg-ink-gold px-1 text-center text-[9px] leading-4 text-ink-black">{count > 99 ? "99+" : count}</span> : null; }

export default function ClientHeaderUtilities({ messages, notifications, unreadMessages, unreadNotifications }: { messages: Message[]; notifications: Notification[]; unreadMessages: number; unreadNotifications: number }) {
  const [messagesOpen, setMessagesOpen] = useState(false); const [notificationsOpen, setNotificationsOpen] = useState(false); const [items, setItems] = useState(notifications);
  async function markAll() { const response = await fetch("/api/client/notifications", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: "all" }) }); if (response.ok) setItems((current) => current.map((item) => ({ ...item, unread: false }))); }
  const icon = "relative flex h-10 w-10 items-center justify-center border border-ink-white/15 text-ink-grey transition-colors hover:border-ink-gold hover:text-ink-gold";
  return <><button type="button" className={icon} aria-label="Wiadomości" onClick={() => setMessagesOpen(true)}><Mail className="h-4 w-4" /><Badge count={unreadMessages} /></button><button type="button" className={icon} aria-label="Powiadomienia" onClick={() => setNotificationsOpen(true)}><Bell className="h-4 w-4" /><Badge count={unreadNotifications} /></button>{messagesOpen && <AppModal title="Wiadomości" size="md" onClose={() => setMessagesOpen(false)}><div className="space-y-2">{messages.length ? messages.map((message) => <Link key={message.id} href={`/app/portal/messages#${message.projectId}`} onClick={() => setMessagesOpen(false)} className={`block border p-3 ${message.unread ? "border-ink-gold/50 bg-ink-gold/5" : "border-ink-white/10"}`}><div className="flex justify-between gap-3"><p className="text-sm">{message.project}</p><time className="text-[10px] text-ink-grey">{new Date(message.createdAt).toLocaleString("pl-PL", { dateStyle: "short", timeStyle: "short" })}</time></div><p className="mt-2 line-clamp-2 text-xs text-ink-grey">{message.body}</p></Link>) : <p className="text-sm text-ink-grey">Brak nowych wiadomości.</p>}</div></AppModal>}{notificationsOpen && <AppModal title="Powiadomienia" size="md" onClose={() => setNotificationsOpen(false)} headerAction={items.some((item) => item.unread) ? <button type="button" onClick={markAll} className="border border-ink-gold/60 px-2 py-2 text-[10px] text-ink-gold">OZNACZ WSZYSTKIE</button> : undefined}><div className="space-y-2">{items.length ? items.map((item) => <Link key={item.id} href={item.href || "/app/portal/notifications"} onClick={() => setNotificationsOpen(false)} className={`block border p-3 ${item.unread ? "border-ink-gold/50 bg-ink-gold/5" : "border-ink-white/10"}`}><div className="flex justify-between gap-3"><p className="text-sm">{item.title}</p><time className="text-[10px] text-ink-grey">{new Date(item.createdAt).toLocaleString("pl-PL", { dateStyle: "short", timeStyle: "short" })}</time></div><p className="mt-2 text-xs text-ink-grey">{item.body}</p></Link>) : <p className="text-sm text-ink-grey">Brak powiadomień.</p>}</div></AppModal>}</>;
}
