"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { isRichText, sanitizeRichText } from "@/lib/richText";

type ClientDocument = { id: string; title: string; category: string; version: number; content: string; accepted: boolean };
const category: Record<string, string> = { consent: "Zgoda", preparation: "Przygotowanie", aftercare: "Pielęgnacja", policy: "Regulamin", other: "Informacja" };

export default function ClientDocuments({ documents }: { documents: ClientDocument[] }) {
  const [open, setOpen] = useState<string | null>(null); const [busy, setBusy] = useState<string | null>(null); const [error, setError] = useState(""); const router = useRouter();
  async function accept(id: string) { setBusy(id); setError(""); try { const res = await fetch(`/api/client/documents/${id}/accept`, { method: "POST" }); const data = await res.json(); if (!res.ok) throw new Error(data.error); router.refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Nie udało się zapisać potwierdzenia."); } finally { setBusy(null); } }
  if (!documents.length) return null;
  return <section className="mt-14"><div className="flex items-end justify-between gap-4"><div><p className="text-[11px] tracking-[0.18em] text-ink-gold">DOKUMENTY</p><h2 className="mt-2 font-display text-3xl">Do przeczytania</h2></div><span className="text-xs text-ink-grey">{documents.filter((d) => !d.accepted).length} oczekuje</span></div><div className="mt-5 divide-y divide-ink-white/10 border border-ink-white/10">{documents.map((document) => <article key={document.id} className="p-5"><button type="button" onClick={() => setOpen(open === document.id ? null : document.id)} aria-expanded={open === document.id} className="flex w-full items-center justify-between gap-4 text-left"><span><span className="block text-base text-ink-white">{document.title}</span><span className="mt-1 block text-[11px] tracking-[0.1em] text-ink-gold">{category[document.category] ?? "DOKUMENT"} · WERSJA {document.version}</span></span><span className="text-xl text-ink-gold">{open === document.id ? "−" : "+"}</span></button>{open === document.id && <div className="mt-5 border-t border-ink-white/10 pt-5">{isRichText(document.content) ? <div className="document-rich-text text-sm leading-relaxed text-ink-grey" dangerouslySetInnerHTML={{ __html: sanitizeRichText(document.content) }} /> : <p className="whitespace-pre-line text-sm leading-relaxed text-ink-grey">{document.content}</p>}<div className="mt-6 flex items-center gap-4">{document.accepted ? <span className="text-xs tracking-[0.08em] text-ink-gold">✓ POTWIERDZONE</span> : <button disabled={busy === document.id} onClick={() => accept(document.id)} className="border border-ink-gold px-4 py-2.5 text-xs tracking-[0.08em] text-ink-gold hover:bg-ink-gold hover:text-ink-black disabled:opacity-50">{busy === document.id ? "ZAPISYWANIE…" : "PRZECZYTAŁEM(-AM) I AKCEPTUJĘ"}</button>}</div></div>}</article>)}</div>{error && <p role="alert" className="mt-3 text-sm text-red-300">{error}</p>}</section>;
}
