"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";

export default function CompleteProfileForm({ initial, returnTo }: { initial: { firstName: string; lastName: string; phone: string | null }; returnTo: string }) {
  const router = useRouter(); const [value, setValue] = useState({ firstName: initial.firstName, lastName: initial.lastName, phone: initial.phone || "" }); const [error, setError] = useState(""); const [saving, setSaving] = useState(false); const [manual, setManual] = useState(false);
  async function save() { setSaving(true); setError(""); try { const response = await fetch("/api/client/profile", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(value) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); router.push(returnTo); router.refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Nie udało się zapisać danych."); } finally { setSaving(false); } }
  return <main className="flex min-h-screen items-center justify-center bg-ink-black p-6 text-ink-white"><section className="w-full max-w-md border border-ink-white/15 p-7"><p className="text-xs tracking-widest text-ink-gold">JESZCZE CHWILA</p><h1 className="mt-3 font-display text-3xl">Uzupełnij podstawowe dane.</h1><p className="mt-2 text-sm text-ink-grey">Możemy wykorzystać podstawowe dane otrzymane przy logowaniu Google. Zawsze możesz je poprawić.</p><div className="mt-5 grid grid-cols-2 gap-2"><button type="button" onClick={() => setManual(false)} className={`border px-3 py-2 text-xs ${!manual ? "border-ink-gold text-ink-gold" : "border-ink-white/20 text-ink-grey"}`}>UŻYJ DANYCH Z GOOGLE</button><button type="button" onClick={() => { setManual(true); setValue({ firstName: "", lastName: "", phone: "" }); }} className={`border px-3 py-2 text-xs ${manual ? "border-ink-gold text-ink-gold" : "border-ink-white/20 text-ink-grey"}`}>UZUPEŁNIĘ RĘCZNIE</button></div><div className="mt-6 space-y-3">{(["firstName", "lastName", "phone"] as const).map((key) => <input key={key} required={key !== "phone"} value={value[key]} onChange={(event) => setValue({ ...value, [key]: event.target.value })} placeholder={{ firstName: "Imię", lastName: "Nazwisko", phone: "Telefon (opcjonalnie)" }[key]} className="w-full border border-ink-white/20 bg-transparent p-3" />)}<button disabled={saving} onClick={save} className="w-full border border-ink-gold bg-ink-gold p-3 text-xs text-ink-black disabled:opacity-50">{saving ? "ZAPISYWANIE…" : "ZAPISZ I PRZEJDŹ DALEJ"}</button>{error && <p className="text-sm text-red-300">{error}</p>}</div></section></main>;
}
