"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import AppModal from "@/components/ui/AppModal";
import AppButton from "@/components/ui/AppButton";
import ConfirmModal from "@/components/ui/ConfirmModal";

export default function ProfileSettings({ client }: { client: { firstName: string; lastName: string; phone: string | null; email?: string; avatarUrl?: string | null } }) {
  const router = useRouter(); const [value, setValue] = useState(client); const [open, setOpen] = useState(false); const [confirmDelete, setConfirmDelete] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function save() { setBusy(true); setMessage(""); try { const response = await fetch("/api/client/profile", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(value) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setMessage("Dane zapisane."); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Nie udało się zapisać danych."); } finally { setBusy(false); } }
  async function remove() { setBusy(true); try { await fetch("/api/client/profile", { method: "DELETE" }); router.push("/app"); router.refresh(); } finally { setBusy(false); } }
  return <section id="profil" className="scroll-mt-6 mt-10 border border-ink-white/15 bg-ink-charcoal/30 p-5"><div className="flex items-center justify-between gap-4"><div className="flex items-center gap-3">{value.avatarUrl ? <img src={value.avatarUrl} alt="Zdjęcie profilowe" className="h-12 w-12 rounded-full border border-ink-gold/50 object-cover" /> : <span className="flex h-12 w-12 items-center justify-center rounded-full border border-ink-gold/50 font-display text-lg text-ink-gold">{value.firstName.slice(0, 1)}{value.lastName.slice(0, 1)}</span>}<div><p className="text-[10px] tracking-[0.14em] text-ink-gold">TWÓJ PROFIL</p><p className="mt-1 text-sm text-ink-white">{value.firstName} {value.lastName}</p>{value.email && <p className="text-xs text-ink-grey">{value.email}</p>}</div></div><AppButton onClick={() => setOpen(true)}>EDYTUJ</AppButton></div>{open && <AppModal title="Edytuj profil" subtitle="Podstawowe dane potrzebne do obsługi wizyt." onClose={busy ? () => undefined : () => setOpen(false)} footer={<div className="flex justify-between gap-3"><AppButton variant="destructive" type="button" onClick={() => setConfirmDelete(true)}>USUŃ KONTO</AppButton><div className="flex gap-2"><AppButton variant="ghost" type="button" onClick={() => setOpen(false)} disabled={busy}>ANULUJ</AppButton><AppButton variant="primary" type="button" onClick={save} disabled={busy}>{busy ? "ZAPIS…" : "ZAPISZ"}</AppButton></div></div>}><div className="grid gap-4 sm:grid-cols-2">{(["firstName", "lastName", "phone"] as const).map((key) => <label key={key} className={`text-[11px] tracking-[0.1em] text-ink-grey ${key === "phone" ? "sm:col-span-2" : ""}`}>{({ firstName: "IMIĘ", lastName: "NAZWISKO", phone: "TELEFON" } as const)[key]}<input value={value[key] ?? ""} onChange={(event) => setValue({ ...value, [key]: event.target.value })} className="mt-2 w-full border border-ink-white/20 bg-ink-black px-3 py-3 text-sm normal-case tracking-normal text-ink-white outline-none focus:border-ink-gold" /></label>)}</div>{message && <p className="mt-4 text-sm text-ink-grey">{message}</p>}</AppModal>}{confirmDelete && <ConfirmModal message="Usunąć konto wraz z projektami i wizytami? Tej operacji nie można cofnąć." onCancel={() => setConfirmDelete(false)} onConfirm={remove} pending={busy} pendingLabel="USUWANIE…" />}</section>;
}
