import Link from "next/link";
import { redirect } from "next/navigation";
import ClientLogoutButton from "@/components/client/ClientLogoutButton";
import InspirationUpload from "@/components/client/InspirationUpload";
import ClientDocuments from "@/components/client/ClientDocuments";
import { getCurrentClient } from "@/lib/clientAuth";
import { prisma } from "@/lib/prisma";

const statusLabel: Record<string, string> = { inquiry: "Otrzymaliśmy zgłoszenie", reviewing: "Projekt jest analizowany", accepted: "Projekt zaakceptowany", scheduled: "Wizyta zaplanowana", completed: "Projekt zakończony", cancelled: "Projekt anulowany" };

export default async function ClientPortalPage() {
  const current = await getCurrentClient(); if (!current) redirect("/app");
  const [client, documents] = await Promise.all([
    prisma.client.findUniqueOrThrow({ where: { id: current.id }, include: { projects: { include: { appointments: { orderBy: { startsAt: "asc" }, take: 1 }, images: true }, orderBy: { updatedAt: "desc" } } } }),
    prisma.studioDocument.findMany({ where: { published: true }, orderBy: { updatedAt: "desc" }, include: { acceptances: { where: { clientId: current.id }, select: { id: true, version: true } } } }),
  ]);
  const clientDocuments = documents.map((document) => ({ ...document, accepted: document.acceptances.some((acceptance) => acceptance.version === document.version) }));
  return <main className="min-h-screen bg-ink-black px-6 py-10 text-ink-white md:px-10"><header className="mx-auto flex max-w-5xl items-center justify-between border-b border-ink-white/15 pb-6"><Link href="/" className="font-display text-2xl tracking-wide">COOLINK</Link><ClientLogoutButton /></header><section className="mx-auto max-w-5xl py-12"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-[11px] tracking-[0.2em] text-ink-gold">TWOJE KONTO</p><h1 className="mt-3 font-display text-4xl md:text-6xl">Cześć, {client.firstName}.</h1></div>{client.projects.length > 0 && <Link href="/app/terminy" className="border border-ink-gold px-4 py-3 text-xs tracking-[0.08em] text-ink-gold hover:bg-ink-gold hover:text-ink-black">ZAPROPONUJ TERMIN</Link>}</div><div className="mt-10 grid gap-5 md:grid-cols-2">{client.projects.length === 0 ? <div className="border border-dashed border-ink-white/25 p-7"><h2 className="font-display text-2xl">Zacznij od pomysłu.</h2><p className="mt-3 text-sm leading-relaxed text-ink-grey">Opowiedz nam o tatuażu, a my poprowadzimy Cię dalej.</p><Link href="/app/new-project" className="mt-6 inline-block border border-ink-gold px-4 py-3 text-xs tracking-[0.1em] text-ink-gold hover:bg-ink-gold hover:text-ink-black">NOWE ZGŁOSZENIE</Link></div> : client.projects.map((project) => <article key={project.id} className="border border-ink-white/15 bg-ink-charcoal/30 p-6"><p className="text-[11px] tracking-[0.13em] text-ink-gold">{statusLabel[project.status] ?? project.status}</p><h2 className="mt-3 font-display text-2xl">{project.title}</h2><p className="mt-3 line-clamp-3 text-sm leading-relaxed text-ink-grey">{project.description}</p>{project.appointments[0] ? <p className="mt-5 border-t border-ink-white/10 pt-4 text-sm text-ink-white">Najbliższa wizyta: {new Intl.DateTimeFormat("pl-PL", { dateStyle: "long", timeStyle: "short" }).format(project.appointments[0].startsAt)}</p> : <p className="mt-5 border-t border-ink-white/10 pt-4 text-sm text-ink-grey">Termin ustalimy po analizie zgłoszenia.</p>}{project.images.length > 0 && <div className="mt-5 grid grid-cols-3 gap-2">{project.images.map((image) => <a key={image.id} href={`/api/client/images/${image.id}`} target="_blank" rel="noreferrer" className="relative aspect-square overflow-hidden border border-ink-white/10"><img src={`/api/client/images/${image.id}`} alt={image.caption || "Inspiracja do projektu"} className="h-full w-full object-cover" /></a>)}</div>}<p className="mt-3 text-xs text-ink-grey">Inspiracje: {project.images.length}</p><InspirationUpload projectId={project.id} /></article>)}</div><ClientDocuments documents={clientDocuments} /></section></main>;
}
