import Link from "next/link";
import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";
import ProjectManager from "@/components/admin/ProjectManager";

const STATUS: Record<string, string> = { inquiry: "NOWE ZGŁOSZENIE", reviewing: "ANALIZA", accepted: "ZAAKCEPTOWANY", scheduled: "ZAPLANOWANY", completed: "ZAKOŃCZONY", cancelled: "ANULOWANY" };
export const dynamic = "force-dynamic";

export default async function ClientProfile({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const client = await prisma.client.findUnique({ where: { id }, include: { projects: { orderBy: { updatedAt: "desc" } } } });
  if (!client) notFound();
  return <div className="flex flex-col gap-8"><Link href="/admin/clients" className="text-xs tracking-[0.08em] text-ink-grey hover:text-ink-gold">← KLIENCI</Link><div><p className="text-[11px] tracking-[0.16em] text-ink-gold">PROFIL KLIENTA</p><h1 className="mt-2 font-display text-4xl text-ink-white">{client.firstName} {client.lastName}</h1><p className="mt-3 text-sm text-ink-grey">{client.email}{client.phone ? ` · ${client.phone}` : ""}</p>{client.tags && <p className="mt-3 text-xs text-ink-gold">{client.tags}</p>}</div><section><div className="mb-4 flex items-end justify-between"><div><p className="text-[11px] tracking-[0.14em] text-ink-gold">PROJEKTY</p><h2 className="mt-2 font-display text-2xl text-ink-white">Historia projektów</h2></div><span className="text-sm text-ink-grey">{client.projects.length}</span></div><div className="flex flex-col gap-5">{client.projects.length === 0 ? <p className="border border-dashed border-ink-white/20 p-7 text-sm text-ink-grey">Klient nie ma jeszcze projektów.</p> : client.projects.map((project) => <article key={project.id} className="border border-ink-white/15 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-lg text-ink-white">{project.title}</h3><p className="mt-2 text-xs tracking-[0.08em] text-ink-gold">{STATUS[project.status] ?? project.status}</p></div><p className="text-xs text-ink-grey">{project.createdAt.toLocaleDateString("pl-PL")}</p></div><p className="mt-5 whitespace-pre-line text-sm leading-relaxed text-ink-grey">{project.description}</p><dl className="mt-5 grid gap-3 text-xs text-ink-grey sm:grid-cols-3"><div><dt className="text-ink-white">Styl</dt><dd className="mt-1">{project.styles || "—"}</dd></div><div><dt className="text-ink-white">Miejsce / rozmiar</dt><dd className="mt-1">{[project.placement, project.size].filter(Boolean).join(" · ") || "—"}</dd></div><div><dt className="text-ink-white">Kolor / termin</dt><dd className="mt-1">{[project.colorPreference, project.preferredDateNote].filter(Boolean).join(" · ") || "—"}</dd></div></dl><div className="mt-6"><ProjectManager id={project.id} initialStatus={project.status} initialNotes={project.internalNotes} estimatedPrice={project.estimatedPrice} finalPrice={project.finalPrice} /></div></article>)}</div></section></div>;
}
