const GOOGLE_AUTH_URL = "https://accounts.google.com/o/oauth2/v2/auth";
const GOOGLE_TOKEN_URL = "https://oauth2.googleapis.com/token";
const GOOGLE_CALENDAR_API = "https://www.googleapis.com/calendar/v3";

export const GOOGLE_CALENDAR_SCOPES = ["https://www.googleapis.com/auth/calendar.calendarlist.readonly", "https://www.googleapis.com/auth/calendar.events"] as const;
export const GOOGLE_CALENDAR_TIME_ZONE = "Europe/Warsaw";

export type GoogleCalendarSummary = { id: string; summary: string; primary?: boolean; accessRole?: string };
export type GoogleEvent = { id: string; status?: string; summary?: string; description?: string; location?: string; updated?: string; colorId?: string; recurringEventId?: string; originalStartTime?: { dateTime?: string; date?: string }; start?: { dateTime?: string; date?: string; timeZone?: string }; end?: { dateTime?: string; date?: string; timeZone?: string } };

function required(name: "GOOGLE_CALENDAR_CLIENT_ID" | "GOOGLE_CALENDAR_CLIENT_SECRET") { const value = process.env[name]; if (!value) throw new Error(`Brak ${name}.`); return value; }
export function googleCalendarRedirectUri(origin?: string) { return process.env.GOOGLE_CALENDAR_REDIRECT_URI || `${origin || process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000"}/api/admin/google-calendar/callback`; }
export function googleCalendarAuthorizationUrl({ state, origin }: { state: string; origin: string }) { const params = new URLSearchParams({ client_id: required("GOOGLE_CALENDAR_CLIENT_ID"), redirect_uri: googleCalendarRedirectUri(origin), response_type: "code", scope: GOOGLE_CALENDAR_SCOPES.join(" "), access_type: "offline", prompt: "consent", include_granted_scopes: "false", state }); return `${GOOGLE_AUTH_URL}?${params}`; }

export async function exchangeGoogleCalendarCode(code: string, origin: string) { const response = await fetch(GOOGLE_TOKEN_URL, { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ code, client_id: required("GOOGLE_CALENDAR_CLIENT_ID"), client_secret: required("GOOGLE_CALENDAR_CLIENT_SECRET"), redirect_uri: googleCalendarRedirectUri(origin), grant_type: "authorization_code" }), cache: "no-store" }); const data = await response.json(); if (!response.ok || !data.refresh_token) throw new Error("Google Calendar nie zwrócił refresh tokenu. Wybierz Połącz ponownie i zaakceptuj dostęp."); return data as { access_token: string; refresh_token: string; expires_in?: number; scope?: string }; }
export async function refreshGoogleCalendarAccessToken(refreshToken: string) { const response = await fetch(GOOGLE_TOKEN_URL, { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ refresh_token: refreshToken, client_id: required("GOOGLE_CALENDAR_CLIENT_ID"), client_secret: required("GOOGLE_CALENDAR_CLIENT_SECRET"), grant_type: "refresh_token" }), cache: "no-store" }); const data = await response.json(); if (!response.ok || !data.access_token) throw new Error("Google Calendar odrzucił odświeżenie dostępu. Połącz integrację ponownie."); return data as { access_token: string; expires_in?: number }; }
export async function googleCalendarRequest<T>(accessToken: string, path: string, init?: RequestInit) { const response = await fetch(`${GOOGLE_CALENDAR_API}${path}`, { ...init, headers: { Authorization: `Bearer ${accessToken}`, "Content-Type": "application/json", ...(init?.headers || {}) }, cache: "no-store" }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(typeof data?.error?.message === "string" ? data.error.message : "Błąd Google Calendar API."); return data as T; }
export function eventRange(event: GoogleEvent) { const allDay = Boolean(event.start?.date && !event.start?.dateTime); const startsAt = new Date(event.start?.dateTime || `${event.start?.date}T00:00:00.000Z`); const endsAt = new Date(event.end?.dateTime || `${event.end?.date}T00:00:00.000Z`); if (Number.isNaN(startsAt.getTime()) || Number.isNaN(endsAt.getTime()) || startsAt >= endsAt) throw new Error("Google event ma nieprawidłowy zakres czasu."); return { startsAt, endsAt, allDay, timeZone: event.start?.timeZone || GOOGLE_CALENDAR_TIME_ZONE }; }
