"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { useToast } from "@/components/admin/ToastProvider";
import ConfirmButton from "@/components/admin/ConfirmButton";
import ColorPicker from "@/components/admin/builder/ColorPicker";
import IconPicker from "@/components/admin/builder/IconPicker";
import AppModal from "@/components/ui/AppModal";

export type CalendarEditorKind = "appointment" | "dayOff" | "freeTerm" | "promotion" | "event" | "workingHours";
export type CalendarEditorItem = { id?: string; kind: CalendarEditorKind; title?: string | null; reason?: string | null; description?: string | null; startsAt: string; endsAt: string; color?: string; icon?: string | null; badge?: string | null; label?: string | null; promoCode?: string | null; ctaLabel?: string | null; ctaUrl?: string | null; active?: boolean; isPublic?: boolean; allDay?: boolean; dates?: string[]; hours?: { startsAt?: string; endsAt?: string; enabled?: boolean; breakStart?: string; breakEnd?: string }; status?: string; price?: number | null; notes?: string | null; clientId?: string; clientName?: string; projectTitle?: string };

function datetime(value: string) { const date = new Date(value); const part = (number: number) => String(number).padStart(2, "0"); return `${date.getFullYear()}-${part(date.getMonth() + 1)}-${part(date.getDate())}T${part(date.getHours())}:${part(date.getMinutes())}`; }

export default function CalendarItemEditor({ item, onClose }: { item: CalendarEditorItem; onClose: () => void }) {
  const router = useRouter(); const { showToast } = useToast(); const [value, setValue] = useState(item); const [saving, setSaving] = useState(false);
  const title = value.kind === "appointment" ? "Wizyta klienta" : value.kind === "dayOff" ? "Niedostępny termin" : value.kind === "freeTerm" ? "Wolny termin" : value.kind === "promotion" ? "Promocja" : value.kind === "event" ? "Wydarzenie" : "Godziny pracy";
  const isSimpleCalendarItem = value.kind === "freeTerm" || value.kind === "promotion" || value.kind === "event";
  const set = (next: Partial<CalendarEditorItem>) => setValue((current) => ({ ...current, ...next }));
  async function submit() { setSaving(true); try { const response = await fetch(value.kind === "appointment" ? `/api/admin/appointments/${value.id}` : "/api/admin/calendar-items", { method: value.id ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(value) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Nie udało się zapisać."); showToast(`${title} ${value.id ? "zaktualizowano" : "dodano"}.`); router.refresh(); onClose(); } catch (error) { showToast(error instanceof Error ? error.message : "Nie udało się zapisać.", "error"); } finally { setSaving(false); } }
  async function remove() { if (!value.id) return; const response = await fetch(`/api/admin/calendar-items?kind=${encodeURIComponent(value.kind)}&id=${encodeURIComponent(value.id)}`, { method: "DELETE" }); const data = await response.json(); if (!response.ok) throw new Error(data.error); showToast(`${title} usunięto.`); router.refresh(); onClose(); }
  async function cancelAppointment() { if (!value.id) return; const response = await fetch(`/api/admin/appointments/${value.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status: "cancelled" }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); showToast("Wizyta została anulowana i pozostała w historii klienta."); router.refresh(); onClose(); }
  return <AppModal title={title} subtitle={value.dates?.length ? `Zaznaczono ${value.dates.length} dni.` : undefined} size={value.kind === "appointment" ? "lg" : "md"} onClose={saving ? () => undefined : onClose} closeOnBackdrop={!saving} footer={<div className="flex flex-wrap items-center gap-3"><button type="button" disabled={saving} onClick={submit} className="border border-ink-gold bg-ink-gold px-4 py-2.5 text-xs tracking-[0.08em] text-ink-black disabled:opacity-50">{saving ? "ZAPIS…" : value.kind === "appointment" ? "ZAPISZ ZMIANY" : "ZAPISZ"}</button>{value.kind === "appointment" && value.clientId && <a href={`/admin/clients/${value.clientId}`} className="px-3 py-2 text-xs text-ink-grey hover:text-ink-white">OTWÓRZ KLIENTA</a>}{value.kind === "appointment" && value.status !== "cancelled" && <ConfirmButton label="ANULUJ WIZYTĘ" confirmText="Anulować wizytę? Termin zostanie usunięty z kalendarza, ale pozostanie w historii klienta jako anulowany." pendingLabel="ANULOWANIE…" onConfirm={cancelAppointment} className="border border-red-400/60 px-4 py-2.5 text-xs tracking-[0.08em] text-red-300" />}{value.id && value.kind !== "appointment" && <ConfirmButton label="USUŃ" confirmText={`Usunąć: ${title}?`} onConfirm={remove} className="border border-red-400/60 px-4 py-2.5 text-xs tracking-[0.08em] text-red-300" />}<button type="button" onClick={onClose} className="px-3 py-2 text-xs text-ink-grey hover:text-ink-white">ANULUJ</button></div>}>
    <div className="grid gap-5">
      {value.kind === "appointment" && <><div className="grid gap-3 border border-ink-gold/40 bg-ink-gold/5 p-3 text-sm sm:grid-cols-2"><div><p className="text-[10px] tracking-widest text-ink-gold">DATA I GODZINA</p><p className="mt-1 text-ink-white">{new Date(value.startsAt).toLocaleString("pl-PL", { dateStyle: "medium", timeStyle: "short" })}</p></div><div><p className="text-[10px] tracking-widest text-ink-gold">DO</p><p className="mt-1 text-ink-white">{new Date(value.endsAt).toLocaleTimeString("pl-PL", { hour: "2-digit", minute: "2-digit" })}</p></div></div><div className="border border-ink-white/10 bg-ink-black/20 p-3 text-sm"><p className="text-ink-white">{value.clientName}</p><p className="mt-1 text-xs text-ink-grey">{value.projectTitle}</p></div><label className="text-[11px] tracking-[0.1em] text-ink-grey">STATUS<select value={value.status ?? "confirmed"} onChange={(event) => set({ status: event.target.value })} className="mt-2 w-full border border-ink-white/15 bg-ink-black px-3 py-2.5 text-sm text-ink-white"><option value="requested">Oczekuje</option><option value="proposed">Propozycja</option><option value="confirmed">Potwierdzona</option><option value="completed">Zakończona</option><option value="no_show">Nieobecność</option><option value="cancelled">Anulowana</option></select></label><label className="text-[11px] tracking-[0.1em] text-ink-grey">CENA (PLN)<input inputMode="numeric" value={value.price ?? ""} onChange={(event) => set({ price: event.target.value === "" ? null : Number(event.target.value) })} className="mt-2 w-full border border-ink-white/15 bg-ink-black px-3 py-2.5 text-sm text-ink-white" /></label><label className="text-[11px] tracking-[0.1em] text-ink-grey">NOTATKA<textarea value={value.notes ?? ""} onChange={(event) => set({ notes: event.target.value })} rows={3} className="mt-2 w-full border border-ink-white/15 bg-ink-black px-3 py-2.5 text-sm text-ink-white" /></label></>}
      {value.kind === "dayOff" && <label className="text-[11px] tracking-[0.1em] text-ink-grey">OPIS<input value={value.reason ?? ""} onChange={(event) => set({ reason: event.target.value })} placeholder="Np. urlop, szkolenie" className="mt-2 w-full border border-ink-white/15 bg-ink-black px-3 py-2.5 text-sm text-ink-white" /></label>}
      {value.kind !== "appointment" && value.kind !== "workingHours" && <div className="grid gap-4 border-b border-ink-white/10 pb-5 sm:grid-cols-2"><label className="text-[11px] tracking-[0.1em] text-ink-gold">DATA I GODZINA OD<input type="datetime-local" step="1800" value={datetime(value.startsAt)} onChange={(event) => set({ startsAt: new Date(event.target.value).toISOString() })} className="mt-2 w-full border border-ink-gold/50 bg-ink-black px-3 py-2.5 text-sm text-ink-white" /></label><label className="text-[11px] tracking-[0.1em] text-ink-gold">DATA I GODZINA DO<input type="datetime-local" step="1800" value={datetime(value.endsAt)} onChange={(event) => set({ endsAt: new Date(event.target.value).toISOString() })} className="mt-2 w-full border border-ink-gold/50 bg-ink-black px-3 py-2.5 text-sm text-ink-white" /></label></div>}
      {isSimpleCalendarItem && <><label className="text-[11px] tracking-[0.1em] text-ink-grey">{value.kind === "promotion" ? "NAZWA PROMOCJI" : value.kind === "event" ? "TYTUŁ WYDARZENIA" : "NAZWA (OPCJONALNIE)"}<input value={value.title ?? ""} onChange={(event) => set({ title: event.target.value })} className="mt-2 w-full border border-ink-white/15 bg-ink-black px-3 py-2.5 text-sm text-ink-white" /></label>{value.kind === "event" && <label className="text-[11px] tracking-[0.1em] text-ink-grey">ETYKIETA<input value={value.label ?? ""} onChange={(event) => set({ label: event.target.value })} placeholder="EVENT, WALK-IN…" className="mt-2 w-full border border-ink-white/15 bg-ink-black px-3 py-2.5 text-sm text-ink-white" /></label>}{value.kind === "promotion" && <label className="text-[11px] tracking-[0.1em] text-ink-grey">BADGE<input value={value.badge ?? ""} onChange={(event) => set({ badge: event.target.value })} placeholder="PROMO" className="mt-2 w-full border border-ink-white/15 bg-ink-black px-3 py-2.5 text-sm text-ink-white" /></label>}<label className="text-[11px] tracking-[0.1em] text-ink-grey">KRÓTKI OPIS (OPCJONALNIE)<textarea rows={3} value={value.description ?? ""} onChange={(event) => set({ description: event.target.value })} className="mt-2 w-full border border-ink-white/15 bg-ink-black px-3 py-2.5 text-sm text-ink-white" /></label><div className="grid gap-4 sm:grid-cols-2"><ColorPicker label="KOLOR" value={value.color ?? (value.kind === "promotion" ? "#C99A4A" : value.kind === "freeTerm" ? "#10B981" : "#6B7280")} onChange={(color) => set({ color })} /><IconPicker value={value.icon ?? ""} onChange={(icon) => set({ icon })} /></div></>}
      {value.kind === "promotion" && <><div className="grid gap-4 sm:grid-cols-2"><label className="text-[11px] tracking-[0.1em] text-ink-grey">KOD PROMO<input value={value.promoCode ?? ""} onChange={(event) => set({ promoCode: event.target.value })} className="mt-2 w-full border border-ink-white/15 bg-ink-black px-3 py-2.5 text-sm text-ink-white" /></label><label className="text-[11px] tracking-[0.1em] text-ink-grey">CTA<input value={value.ctaLabel ?? ""} onChange={(event) => set({ ctaLabel: event.target.value })} className="mt-2 w-full border border-ink-white/15 bg-ink-black px-3 py-2.5 text-sm text-ink-white" /></label></div><fieldset className="flex flex-wrap gap-5"><legend className="mb-2 text-[11px] tracking-[0.1em] text-ink-grey">WIDOCZNOŚĆ PROMOCJI</legend><label className="flex items-center gap-2 text-sm"><input type="radio" checked={Boolean(value.isPublic)} onChange={() => set({ isPublic: true })} />PUBLICZNE</label><label className="flex items-center gap-2 text-sm"><input type="radio" checked={!value.isPublic} onChange={() => set({ isPublic: false })} />TYLKO ZALOGOWANI</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={value.active !== false} onChange={(event) => set({ active: event.target.checked })} />AKTYWNE</label></fieldset></>}
      {value.kind === "event" && <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={Boolean(value.allDay)} onChange={(event) => set({ allDay: event.target.checked })} />CAŁY DZIEŃ</label>}
    </div>
  </AppModal>;
}
