"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { useToast } from "@/components/admin/ToastProvider";

export type RecurringHours = { weekday: number; enabled: boolean; startsAt: string; endsAt: string };
const labels = ["Niedziela", "Poniedziałek", "Wtorek", "Środa", "Czwartek", "Piątek", "Sobota"];

export default function RecurringHoursEditor({ initialHours, bufferMinutes }: { initialHours: RecurringHours[]; bufferMinutes: number }) {
  const router = useRouter(); const { showToast } = useToast();
  const [hours, setHours] = useState<RecurringHours[]>(Array.from({ length: 7 }, (_, weekday) => initialHours.find((item) => item.weekday === weekday) ?? { weekday, enabled: weekday !== 0, startsAt: "10:00", endsAt: "19:00" }));
  const [buffer, setBuffer] = useState(bufferMinutes); const [applyDays, setApplyDays] = useState<number[]>([1, 2, 3, 4, 5]); const [bulkStart, setBulkStart] = useState("10:00"); const [bulkEnd, setBulkEnd] = useState("19:00"); const [saving, setSaving] = useState(false);
  const edit = (weekday: number, patch: Partial<RecurringHours>) => setHours((items) => items.map((item) => item.weekday === weekday ? { ...item, ...patch } : item));
  const toggleDay = (weekday: number) => setApplyDays((days) => days.includes(weekday) ? days.filter((day) => day !== weekday) : [...days, weekday]);
  const apply = () => { if (bulkStart >= bulkEnd) return showToast("Godzina zakończenia musi być później niż rozpoczęcie.", "error"); setHours((items) => items.map((item) => applyDays.includes(item.weekday) ? { ...item, enabled: true, startsAt: bulkStart, endsAt: bulkEnd } : item)); };
  async function save() { setSaving(true); try { const response = await fetch("/api/admin/availability", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ hours, bufferMinutes: buffer }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); showToast("Stałe godziny pracy zapisane."); router.refresh(); } catch (error) { showToast(error instanceof Error ? error.message : "Nie udało się zapisać godzin.", "error"); } finally { setSaving(false); } }
  return <section className="border border-ink-white/10 bg-ink-charcoal/40 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[10px] tracking-[0.15em] text-ink-gold">STAŁE GODZINY PRACY</p><p className="mt-1 text-xs text-ink-grey">Obowiązują co tydzień. Wyjątek dla daty ustawisz po kliknięciu dnia w kalendarzu.</p></div><button type="button" disabled={saving} onClick={save} className="border border-ink-gold px-3 py-2 text-[11px] text-ink-gold disabled:opacity-50">{saving ? "ZAPIS…" : "ZAPISZ STAŁE GODZINY"}</button></div><label className="mt-4 flex max-w-xs items-center justify-between gap-3 border border-ink-white/10 px-3 py-2 text-xs text-ink-grey">BUFOR MIĘDZY WIZYTAMI<input aria-label="Bufor między wizytami" type="number" min="0" max="240" step="5" value={buffer} onChange={(event) => setBuffer(Number(event.target.value))} className="w-20 border border-ink-white/15 bg-ink-black p-1.5 text-ink-white" />min</label><div className="mt-4 space-y-2">{hours.map((item) => <div key={item.weekday} className="grid grid-cols-[1fr_auto_auto] items-center gap-2 border border-ink-white/10 px-3 py-2 text-xs"><label className="flex items-center gap-2"><input type="checkbox" checked={item.enabled} onChange={(event) => edit(item.weekday, { enabled: event.target.checked })} />{labels[item.weekday]}</label><input aria-label={`${labels[item.weekday]} od`} type="time" disabled={!item.enabled} value={item.startsAt} onChange={(event) => edit(item.weekday, { startsAt: event.target.value })} className="w-24 border border-ink-white/15 bg-ink-black p-1.5 disabled:opacity-40" /><input aria-label={`${labels[item.weekday]} do`} type="time" disabled={!item.enabled} value={item.endsAt} onChange={(event) => edit(item.weekday, { endsAt: event.target.value })} className="w-24 border border-ink-white/15 bg-ink-black p-1.5 disabled:opacity-40" /></div>)}</div><div className="mt-4 border-t border-ink-white/10 pt-4"><p className="text-[10px] tracking-[0.12em] text-ink-grey">ZASTOSUJ DO…</p><div className="mt-2 flex flex-wrap gap-2">{labels.map((label, weekday) => <label key={label} className="flex items-center gap-1 text-xs"><input type="checkbox" checked={applyDays.includes(weekday)} onChange={() => toggleDay(weekday)} />{label.slice(0, 3)}</label>)}</div><div className="mt-3 flex flex-wrap items-end gap-3"><label className="text-xs text-ink-grey">OD<input type="time" value={bulkStart} onChange={(event) => setBulkStart(event.target.value)} className="mt-1 block border border-ink-white/15 bg-ink-black p-2 text-ink-white" /></label><label className="text-xs text-ink-grey">DO<input type="time" value={bulkEnd} onChange={(event) => setBulkEnd(event.target.value)} className="mt-1 block border border-ink-white/15 bg-ink-black p-2 text-ink-white" /></label><button type="button" onClick={apply} className="border border-ink-white/25 px-3 py-2 text-xs">ZASTOSUJ</button></div></div></section>;
}
