"use client";

import { Globe2 } from "lucide-react";
import { useContext } from "react";
import InspectorPopover, { InspectorTheme } from "./InspectorPopover";

const CREATIVE_PALETTE = ["#090807", "#111111", "#24211e", "#f5f1e8", "#ffffff", "#c99a4a", "#f0bc62", "#8d5a2b", "#7f1d1d", "#dc2626", "#fb7185", "#7c3aed", "#2563eb", "#06b6d4", "#059669", "#84cc16"];

export default function ColorPicker({ value = "", onChange, label = "KOLOR", palette = true }: { value?: string; onChange: (value: string) => void; label?: string; palette?: boolean }) {
  const theme = useContext(InspectorTheme);
  const token = /^var\((--color-ink-[a-z-]+)\)$/.exec(value)?.[1];
  const resolved = token ? (theme as Record<string, string>)[token] ?? value : value;
  const safe = /^#[0-9a-f]{6}$/i.test(resolved) ? resolved : "#c99a4a";
  return <div className="flex min-w-0 items-center justify-between gap-2 py-1 text-[10px] text-white/75"><span className="min-w-0 break-words">{label}</span><div className="flex shrink-0 gap-1"><InspectorPopover title={`${label} — kolory globalne`} icon={<Globe2 aria-hidden className="h-3.5 w-3.5" />}>{[["Akcent", "gold"], ["Tekst", "white"], ["Tekst pomocniczy", "grey"], ["Tło", "black"], ["Powierzchnia", "charcoal"], ["Jasny akcent", "gold-bright"]].map(([name, token]) => <button key={token} type="button" onClick={() => onChange(`var(--color-ink-${token})`)} aria-pressed={value === `var(--color-ink-${token})`} className="flex min-h-8 items-center gap-2 rounded px-2 text-left text-xs aria-pressed:bg-ink-gold/15 aria-pressed:text-ink-gold hover:bg-white/10"><span className="h-4 w-4 rounded border border-white/20" style={{ backgroundColor: `var(--color-ink-${token})` }} />{name}</button>)}<p className="text-[10px] text-white/65">Powiązane z motywem strony — zmiana globalna aktualizuje widgety.</p></InspectorPopover><InspectorPopover title={`${label} — selektor`} summary={value || "Domyślny"} icon={<span className="h-4 w-4 rounded-sm border border-white/30" style={{ backgroundColor: resolved || "transparent" }} />}><input aria-label={`${label} — próbnik`} type="color" value={safe} onChange={(e) => onChange(e.target.value)} className="h-24 w-full cursor-pointer rounded border border-white/20 bg-transparent p-1" /><label className="text-[10px] text-white/75">HEX / CSS<input aria-label={`${label} — wartość`} value={value} onChange={(e) => onChange(e.target.value)} placeholder="#FFFFFF lub transparent" className="mt-1 h-8 w-full min-w-0 rounded border border-white/20 bg-[#17191c] px-2 text-[11px] text-white outline-none focus-visible:border-ink-gold" /></label>{palette && <span className="grid grid-cols-8 gap-1" role="group" aria-label="Dodatkowa paleta kolorów">{CREATIVE_PALETTE.map((color) => <button key={color} type="button" title={color} aria-label={`Ustaw kolor ${color}`} aria-pressed={value.toLowerCase() === color} onClick={() => onChange(color)} className="h-7 rounded border border-white/20 aria-pressed:ring-2 aria-pressed:ring-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-ink-gold" style={{ backgroundColor: color }} />)}</span>}<div className="flex gap-3 text-xs"><button type="button" onClick={() => onChange("transparent")} className="text-white/80 underline">Przezroczysty</button><button type="button" onClick={() => onChange("")} className="text-ink-gold underline">Reset</button></div></InspectorPopover></div></div>;
}
