"use client";

import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { useToast } from "@/components/admin/ToastProvider";

type Hours = { weekday: number; enabled: boolean; startsAt: string; endsAt: string };
type Block = { id: string; startsAt: string; endsAt: string; reason: string | null };
type Promotion = { id: string; title: string; description: string | null; badge: string | null; startsAt: string; endsAt: string; active: boolean };
const days = ["Niedziela", "Poniedziałek", "Wtorek", "Środa", "Czwartek", "Piątek", "Sobota"];

export default function AvailabilityManager({ initialHours, bufferMinutes, blocks, promotions }: { initialHours: Hours[]; bufferMinutes: number; blocks: Block[]; promotions: Promotion[] }) {
  const router = useRouter(); const { showToast } = useToast();
  const [hours, setHours] = useState(initialHours); const [buffer, setBuffer] = useState(String(bufferMinutes)); const [saving, setSaving] = useState(false);
  const [block, setBlock] = useState({ startsAt: "", endsAt: "", reason: "" });
  const [promo, setPromo] = useState({ title: "", description: "", badge: "PROMO", startsAt: "", endsAt: "" });

  async function saveHours() { setSaving(true); try { const res = await fetch("/api/admin/availability", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ hours, bufferMinutes: Number(buffer) }) }); const data = await res.json(); if (!res.ok) throw new Error(data.error); showToast("Godziny pracy i bufor zapisane."); } catch (error) { showToast(error instanceof Error ? error.message : "Nie udało się zapisać godzin.", "error"); } finally { setSaving(false); } }
  async function add(kind: "block" | "promotion", event: FormEvent) { event.preventDefault(); const values = kind === "block" ? { kind, ...block } : { kind, ...promo }; try { const res = await fetch("/api/admin/availability", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(values) }); const data = await res.json(); if (!res.ok) throw new Error(data.error); showToast(kind === "block" ? "Termin został wyłączony." : "Promocja została dodana."); if (kind === "block") setBlock({ startsAt: "", endsAt: "", reason: "" }); else setPromo({ title: "", description: "", badge: "PROMO", startsAt: "", endsAt: "" }); router.refresh(); } catch (error) { showToast(error instanceof Error ? error.message : "Nie udało się zapisać.", "error"); } }

  return <div className="grid gap-6 xl:grid-cols-2">
    <section className="border border-ink-white/10 bg-ink-charcoal/30 p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-[11px] tracking-[0.14em] text-ink-gold">DOSTĘPNOŚĆ</p><h2 className="mt-2 font-display text-2xl">Godziny pracy</h2><p className="mt-2 text-sm text-ink-grey">Wyłączony dzień nie pokaże klientowi wolnych terminów.</p></div><button type="button" onClick={saveHours} disabled={saving} className="border border-ink-gold px-3 py-2 text-[11px] text-ink-gold disabled:opacity-50">{saving ? "ZAPIS…" : "ZAPISZ"}</button></div><label className="mt-5 flex max-w-xs flex-col gap-2 text-[11px] tracking-[0.1em] text-ink-grey">BUFOR MIĘDZY WIZYTAMI (MIN)<select value={buffer} onChange={(event) => setBuffer(event.target.value)} className="border border-ink-white/15 bg-ink-black px-3 py-2 text-sm text-ink-white">{[0,5,10,15,20,30,45,60,90,120].map((minutes) => <option key={minutes} value={minutes}>{minutes === 0 ? "Bez bufora" : `${minutes} minut`}</option>)}</select><span className="normal-case tracking-normal">Klient nie zobaczy terminu zbyt blisko poprzedniej wizyty.</span></label><div className="mt-5 divide-y divide-ink-white/10">{hours.map((item, index) => <div key={item.weekday} className="grid grid-cols-[1fr_auto_auto] items-center gap-3 py-3"><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={item.enabled} onChange={(event) => setHours((prev) => prev.map((day) => day.weekday === item.weekday ? { ...day, enabled: event.target.checked } : day))} className="h-4 w-4 accent-[#c99a4a]" />{days[item.weekday]}</label><input aria-label={`${days[item.weekday]} od`} disabled={!item.enabled} type="time" value={item.startsAt} onChange={(event) => setHours((prev) => prev.map((day) => day.weekday === item.weekday ? { ...day, startsAt: event.target.value } : day))} className="w-24 border border-ink-white/15 bg-ink-black px-2 py-1.5 text-xs disabled:opacity-30" /><input aria-label={`${days[item.weekday]} do`} disabled={!item.enabled} type="time" value={item.endsAt} onChange={(event) => setHours((prev) => prev.map((day) => day.weekday === item.weekday ? { ...day, endsAt: event.target.value } : day))} className="w-24 border border-ink-white/15 bg-ink-black px-2 py-1.5 text-xs disabled:opacity-30" /></div>)}</div></section>
    <section className="border border-ink-white/10 bg-ink-charcoal/30 p-5"><p className="text-[11px] tracking-[0.14em] text-ink-gold">WYJĄTKI</p><h2 className="mt-2 font-display text-2xl">Dni wolne i przerwy</h2><form onSubmit={(event) => add("block", event)} className="mt-5 grid gap-3"><div className="grid gap-3 sm:grid-cols-2"><input required type="datetime-local" value={block.startsAt} onChange={(event) => setBlock({ ...block, startsAt: event.target.value })} className="border border-ink-white/15 bg-ink-black px-3 py-2 text-sm" /><input required type="datetime-local" value={block.endsAt} onChange={(event) => setBlock({ ...block, endsAt: event.target.value })} className="border border-ink-white/15 bg-ink-black px-3 py-2 text-sm" /></div><input value={block.reason} onChange={(event) => setBlock({ ...block, reason: event.target.value })} placeholder="Np. urlop, dzień wolny, szkolenie" className="border border-ink-white/15 bg-ink-black px-3 py-2 text-sm" /><button className="justify-self-start border border-ink-white/20 px-3 py-2 text-xs hover:border-ink-gold">+ DODAJ WYŁĄCZENIE</button></form><div className="mt-5 divide-y divide-ink-white/10">{blocks.length === 0 ? <p className="py-3 text-sm text-ink-grey">Brak zaplanowanych wyłączeń.</p> : blocks.map((item) => <div key={item.id} className="py-3 text-sm"><p>{new Date(item.startsAt).toLocaleString("pl-PL", { dateStyle: "medium", timeStyle: "short" })} — {new Date(item.endsAt).toLocaleString("pl-PL", { dateStyle: "medium", timeStyle: "short" })}</p><p className="mt-1 text-xs text-ink-grey">{item.reason || "Niedostępny"}</p></div>)}</div></section>
    <section className="border border-ink-white/10 bg-ink-charcoal/30 p-5 xl:col-span-2"><p className="text-[11px] tracking-[0.14em] text-ink-gold">KALENDARZ KLIENTA</p><h2 className="mt-2 font-display text-2xl">Promocje na terminy</h2><p className="mt-2 text-sm text-ink-grey">Promocja będzie widoczna przy terminie zarówno w Twoim kalendarzu, jak i u klienta.</p><form onSubmit={(event) => add("promotion", event)} className="mt-5 grid gap-3 lg:grid-cols-5"><input required value={promo.title} onChange={(event) => setPromo({ ...promo, title: event.target.value })} placeholder="Nazwa promocji" className="border border-ink-white/15 bg-ink-black px-3 py-2 text-sm" /><input value={promo.badge} onChange={(event) => setPromo({ ...promo, badge: event.target.value })} placeholder="Etykieta, np. PROMO" className="border border-ink-white/15 bg-ink-black px-3 py-2 text-sm" /><input required type="date" value={promo.startsAt} onChange={(event) => setPromo({ ...promo, startsAt: event.target.value })} className="border border-ink-white/15 bg-ink-black px-3 py-2 text-sm" /><input required type="date" value={promo.endsAt} onChange={(event) => setPromo({ ...promo, endsAt: event.target.value })} className="border border-ink-white/15 bg-ink-black px-3 py-2 text-sm" /><button className="border border-ink-gold px-3 py-2 text-xs text-ink-gold hover:bg-ink-gold hover:text-ink-black">+ DODAJ PROMO</button><textarea value={promo.description} onChange={(event) => setPromo({ ...promo, description: event.target.value })} placeholder="Krótki opis promocji (opcjonalnie)" className="min-h-20 border border-ink-white/15 bg-ink-black px-3 py-2 text-sm lg:col-span-5" /></form><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{promotions.length === 0 ? <p className="text-sm text-ink-grey">Nie ma aktywnych promocji.</p> : promotions.map((item) => <div key={item.id} className="border border-ink-gold/25 bg-ink-gold/5 p-4"><p className="text-[10px] tracking-[0.12em] text-ink-gold">{item.badge || "PROMO"}</p><p className="mt-2 text-sm text-ink-white">{item.title}</p><p className="mt-1 text-xs text-ink-grey">{new Date(item.startsAt).toLocaleDateString("pl-PL")} – {new Date(item.endsAt).toLocaleDateString("pl-PL")}</p></div>)}</div></section>
  </div>;
}
