"use client";

import { useMemo, useState } from "react";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import AppButton from "@/components/ui/AppButton";
import AppModal from "@/components/ui/AppModal";
import ProjectManager from "@/components/admin/ProjectManager";
import ProjectSessionsManager from "@/components/admin/ProjectSessionsManager";
import ProjectChat from "@/components/projects/ProjectChat";
import NewAppointmentForm from "@/components/admin/NewAppointmentForm";
import { useToast } from "@/components/admin/ToastProvider";

type Project = { id: string; title: string; description: string; status: string; internalNotes: string | null; estimatedPrice: number | null; finalPrice: number | null; depositStatus: string; depositAmount: number | null; depositPaymentMethod: string | null; appointments: { id: string; startsAt: string; endsAt: string; status: string; notes: string | null; price: number | null }[]; activities: { id: string; message: string; createdAt: string }[]; messages: { id: string; author: string; body: string; createdAt: string; readAt: string | null; attachment: { id: string; caption: string | null } | null }[] };
type Client = { id: string; firstName: string; lastName: string; email: string; phone: string | null; tags: string; notes: string | null };
const views = ["summary", "projects", "appointments", "messages", "history"] as const;
type View = typeof views[number];
const labels: Record<View, string> = { summary: "PODSUMOWANIE", projects: "PROJEKTY", appointments: "WIZYTY", messages: "WIADOMOŚCI", history: "HISTORIA" };

export default function ClientWorkspace({ client, projects }: { client: Client; projects: Project[] }) {
  const router = useRouter(); const pathname = usePathname(); const params = useSearchParams();
  const { showToast } = useToast();
  const view = views.includes(params.get("view") as View) ? params.get("view") as View : "summary";
  const [editing, setEditing] = useState(false); const [details, setDetails] = useState<Project | null>(null); const [values, setValues] = useState(client); const [saving, setSaving] = useState(false); const [newProject, setNewProject] = useState(false); const [projectValues, setProjectValues] = useState({ title: "", description: "" });
  const nextAppointment = useMemo(() => projects.flatMap((project) => project.appointments.map((appointment) => ({ ...appointment, project: project.title }))).filter((appointment) => new Date(appointment.startsAt) >= new Date() && appointment.status !== "cancelled").sort((a,b) => +new Date(a.startsAt)-+new Date(b.startsAt))[0], [projects]);
  const activeProjects = projects.filter((project) => !["cancelled", "completed"].includes(project.status));
  const setView = (next: View) => { const query = new URLSearchParams(params.toString()); query.set("view", next); router.push(`${pathname}?${query}`); };
  async function save() { setSaving(true); try { const response = await fetch(`/api/admin/clients/${client.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(values) }); if (!response.ok) throw new Error((await response.json()).error || "Nie udało się zapisać danych."); setEditing(false); showToast("Dane klienta zapisane."); router.refresh(); } catch (error) { showToast(error instanceof Error ? error.message : "Nie udało się zapisać danych.", "error"); } finally { setSaving(false); } }
  async function createProject() { setSaving(true); try { const response = await fetch("/api/admin/projects", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ clientId: client.id, ...projectValues }) }); if (!response.ok) throw new Error((await response.json()).error || "Nie udało się utworzyć projektu."); setNewProject(false); setProjectValues({ title: "", description: "" }); setView("projects"); showToast("Projekt utworzony."); router.refresh(); } catch (error) { showToast(error instanceof Error ? error.message : "Nie udało się utworzyć projektu.", "error"); } finally { setSaving(false); } }
  const calendarProjects = projects.map((project) => ({ id: project.id, title: project.title, client: { firstName: client.firstName, lastName: client.lastName } }));
  const activity = projects.flatMap((project) => project.activities.map((item) => ({ ...item, project: project.title }))).sort((a,b) => +new Date(b.createdAt)-+new Date(a.createdAt));
  return <section className="space-y-6">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[11px] tracking-widest text-ink-gold">KLIENT</p><h1 className="mt-2 font-display text-4xl">{client.firstName} {client.lastName}</h1></div><div className="flex flex-wrap gap-2"><NewAppointmentForm projects={calendarProjects} label="WIZYTA" /><AppButton variant="secondary" onClick={() => setNewProject(true)}>PROJEKT</AppButton><AppButton variant="secondary" onClick={() => setView("messages")}>NAPISZ WIADOMOŚĆ</AppButton></div></div>
    <nav aria-label="Widoki klienta" className="flex gap-1 overflow-x-auto border-y border-ink-white/10 py-2">{views.map((item) => <button key={item} type="button" onClick={() => setView(item)} className={`shrink-0 px-3 py-2 text-[11px] tracking-[.08em] ${view === item ? "border-b-2 border-ink-gold text-ink-gold" : "text-ink-grey hover:text-ink-white"}`}>{labels[item]}</button>)}</nav>
    {view === "summary" && <div className="grid gap-4 lg:grid-cols-2"><article className="border border-ink-white/15 bg-ink-charcoal/20 p-5"><div className="flex justify-between gap-3"><div><p className="text-[10px] tracking-widest text-ink-gold">DANE KLIENTA</p><p className="mt-3 text-sm">{client.email}</p><p className="mt-1 text-sm text-ink-grey">{client.phone || "Brak telefonu"}</p><p className="mt-3 text-xs text-ink-grey">{client.tags || "Bez tagów"}</p></div><AppButton variant="ghost" onClick={() => setEditing(true)}>EDYTUJ DANE</AppButton></div></article><article className="border border-ink-white/15 bg-ink-charcoal/20 p-5"><p className="text-[10px] tracking-widest text-ink-gold">NAJBLIŻSZA WIZYTA</p>{nextAppointment ? <><p className="mt-3 text-lg">{new Date(nextAppointment.startsAt).toLocaleString("pl-PL", { dateStyle: "medium", timeStyle: "short" })}</p><p className="mt-1 text-sm text-ink-grey">{nextAppointment.project} · {nextAppointment.status}</p></> : <p className="mt-3 text-sm text-ink-grey">Brak zaplanowanej wizyty.</p>}</article><article className="border border-ink-white/15 bg-ink-charcoal/20 p-5"><p className="text-[10px] tracking-widest text-ink-gold">AKTYWNE PROJEKTY</p><p className="mt-3 font-display text-3xl">{activeProjects.length}</p><p className="mt-1 text-sm text-ink-grey">{activeProjects[0]?.title || "Brak aktywnego projektu"}</p></article><article className="border border-ink-white/15 bg-ink-charcoal/20 p-5"><p className="text-[10px] tracking-widest text-ink-gold">OSTATNIA AKTYWNOŚĆ</p><div className="mt-3 space-y-2">{activity.slice(0,3).map((item) => <p key={item.id} className="text-sm text-ink-grey">{item.message}</p>)}{!activity.length && <p className="text-sm text-ink-grey">Brak wpisów.</p>}</div></article></div>}
    {view === "projects" && <div className="grid gap-3 md:grid-cols-2">{projects.map((project) => <button key={project.id} type="button" onClick={() => setDetails(project)} className="border border-ink-white/15 bg-ink-charcoal/20 p-5 text-left hover:border-ink-gold"><div className="flex justify-between gap-3"><h2 className="font-display text-2xl">{project.title}</h2><span className="text-xs text-ink-gold">{project.status}</span></div><p className="mt-3 line-clamp-2 text-sm text-ink-grey">{project.description}</p><p className="mt-4 text-xs text-ink-grey">Sesje: {project.appointments.length} · Zadatek: {project.depositAmount ? `${project.depositAmount} zł` : "—"}</p></button>)}{!projects.length && <p className="text-sm text-ink-grey">Brak projektów klienta.</p>}</div>}
    {view === "appointments" && <div className="space-y-5">{projects.map((project) => <ProjectSessionsManager key={project.id} sessions={project.appointments.map((item) => ({ ...item, startsAt: new Date(item.startsAt), endsAt: new Date(item.endsAt) }))} />)}{!projects.length && <p className="text-sm text-ink-grey">Brak wizyt.</p>}</div>}
    {view === "messages" && <div className="space-y-4">{projects.map((project, index) => <ProjectChat key={project.id} projectId={project.id} role="admin" initial={project.messages} autoFocus={index === 0} />)}{!projects.length && <p className="text-sm text-ink-grey">Utwórz projekt, aby rozpocząć rozmowę.</p>}</div>}
    {view === "history" && <div className="space-y-3">{activity.map((item) => <article key={item.id} className="border-l border-ink-gold/50 pl-4"><p className="text-sm">{item.message}</p><p className="mt-1 text-xs text-ink-grey">{item.project} · {new Date(item.createdAt).toLocaleString("pl-PL", { dateStyle: "medium", timeStyle: "short" })}</p></article>)}{!activity.length && <p className="text-sm text-ink-grey">Historia pojawi się po pierwszych działaniach.</p>}</div>}
    {editing && <AppModal title="Edytuj dane klienta" onClose={() => setEditing(false)} footer={<div className="flex justify-end gap-2"><AppButton variant="ghost" onClick={() => setEditing(false)}>ANULUJ</AppButton><AppButton disabled={saving} onClick={save}>{saving ? "ZAPIS…" : "ZAPISZ"}</AppButton></div>}><div className="grid gap-4 sm:grid-cols-2">{(["firstName", "lastName", "email", "phone", "tags"] as const).map((field) => <label key={field} className={`text-xs text-ink-grey ${field === "tags" ? "sm:col-span-2" : ""}`}>{({ firstName: "IMIĘ", lastName: "NAZWISKO", email: "E-MAIL", phone: "TELEFON", tags: "TAGI" } as const)[field]}<input value={values[field] || ""} onChange={(event) => setValues({ ...values, [field]: event.target.value })} className="mt-2 w-full border border-ink-white/20 bg-transparent p-3 text-sm text-ink-white" /></label>)}</div></AppModal>}
    {newProject && <AppModal title="Nowy projekt" subtitle={`Projekt dla ${client.firstName} ${client.lastName}`} onClose={() => setNewProject(false)} footer={<div className="flex justify-end gap-2"><AppButton variant="ghost" onClick={() => setNewProject(false)}>ANULUJ</AppButton><AppButton disabled={saving || !projectValues.title.trim() || !projectValues.description.trim()} onClick={createProject}>{saving ? "ZAPIS…" : "UTWÓRZ PROJEKT"}</AppButton></div>}><div className="grid gap-4"><label className="text-xs text-ink-grey">NAZWA<input value={projectValues.title} onChange={(event) => setProjectValues({ ...projectValues, title: event.target.value })} className="mt-2 w-full border border-ink-white/20 bg-transparent p-3 text-sm text-ink-white" /></label><label className="text-xs text-ink-grey">OPIS<textarea rows={5} value={projectValues.description} onChange={(event) => setProjectValues({ ...projectValues, description: event.target.value })} className="mt-2 w-full border border-ink-white/20 bg-transparent p-3 text-sm text-ink-white" /></label></div></AppModal>}
    {details && <AppModal title={details.title} subtitle="Workspace projektu" size="xl" onClose={() => setDetails(null)}><ProjectManager id={details.id} clientId={client.id} initialStatus={details.status} initialNotes={details.internalNotes} estimatedPrice={details.estimatedPrice} finalPrice={details.finalPrice} initialDepositStatus={details.depositStatus} depositAmount={details.depositAmount} depositPaymentMethod={details.depositPaymentMethod} /></AppModal>}
  </section>;
}
