"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import CompactDisclosure from "@/components/ui/CompactDisclosure";

type Item = { id: string; name: string; sku: string | null; category: string; unit: string; quantity: number; minimumStock: number; unitCostCents: number | null };
export default function InventoryManager({ items }: { items: Item[] }) {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function submit(form: FormData) { setBusy(true); setMessage(""); const body = Object.fromEntries(form); try { const response = await fetch("/api/admin/inventory", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setMessage("Pozycja dodana."); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Nie udało się zapisać."); } finally { setBusy(false); } }
  async function adjust(id: string, form: FormData) { setBusy(true); setMessage(""); try { const response = await fetch(`/api/admin/inventory/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(form)) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Nie udało się zapisać."); } finally { setBusy(false); } }
  const input = "border border-ink-white/25 bg-ink-black px-3 py-3 text-sm text-ink-white";
  return <div className="space-y-4"><CompactDisclosure title="DODAJ POZYCJĘ" summary="Nowy materiał, stan minimalny i koszt"><form action={submit} className="grid gap-3 sm:grid-cols-2 xl:grid-cols-7"><input name="name" required maxLength={120} placeholder="Nazwa" aria-label="Nazwa" className={`${input} xl:col-span-2`} /><input name="sku" placeholder="SKU (opcjonalnie)" aria-label="SKU" className={input} /><input name="category" defaultValue="materiały" placeholder="Kategoria" aria-label="Kategoria" className={input} /><input name="unit" defaultValue="szt." placeholder="Jednostka" aria-label="Jednostka" className={input} /><input name="quantity" type="number" min="0" defaultValue="0" aria-label="Stan początkowy" className={input} /><input name="minimumStock" type="number" min="0" defaultValue="0" aria-label="Stan minimalny" className={input} /><input name="unitCost" type="number" min="0" step="0.01" defaultValue="0" aria-label="Cena jednostkowa w PLN" className={input} /><button disabled={busy} className="border border-ink-gold bg-ink-gold px-4 py-3 text-xs text-ink-black xl:col-span-2">DODAJ DO MAGAZYNU</button></form></CompactDisclosure>{message && <p role="status" className="text-sm text-ink-gold">{message}</p>}<section className="space-y-3">{items.length ? items.map((item) => { const low = item.quantity <= item.minimumStock; return <article key={item.id} className={`grid gap-3 border p-3 lg:grid-cols-[1fr_auto_360px] lg:items-center ${low ? "border-red-400/50 bg-red-500/5" : "border-ink-white/15"}`}><div><div className="flex flex-wrap items-center gap-2"><h3 className="text-sm">{item.name}</h3>{low && <span className="border border-red-400/50 px-2 py-1 text-[9px] text-red-300">NISKI STAN</span>}</div><p className="mt-1 text-[11px] text-ink-grey">{item.category}{item.sku ? ` · ${item.sku}` : ""}{item.unitCostCents != null ? ` · ${(item.unitCostCents / 100).toFixed(2)} PLN / ${item.unit}` : ""}</p></div><p className="font-display text-2xl text-ink-gold">{item.quantity} <span className="font-body text-[10px] text-ink-grey">{item.unit} / min. {item.minimumStock}</span></p><form action={(form) => adjust(item.id, form)} className="grid grid-cols-[80px_1fr_auto] gap-2"><input name="delta" required type="number" placeholder="np. -2" aria-label={`Zmiana ilości ${item.name}`} className={input} /><select name="reason" aria-label="Powód zmiany" className={input}><option value="zakup">Zakup</option><option value="zużycie">Zużycie</option><option value="korekta">Korekta</option><option value="strata">Strata</option></select><button disabled={busy} className="border border-ink-gold px-3 text-xs text-ink-gold">ZAPISZ</button></form></article>; }) : <p className="border border-dashed border-ink-white/20 p-10 text-center text-sm text-ink-grey">Magazyn jest pusty. Dodaj pierwszą pozycję powyżej.</p>}</section></div>;
}
