"use client";
import { useEffect, useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { useToast } from "@/components/admin/ToastProvider";
import AppModal from "@/components/ui/AppModal";

export default function NewAppointmentForm({ projects, label = "+ ZAPLANUJ WIZYTĘ" }: { projects: { id: string; title: string; client: { firstName: string; lastName: string } }[]; label?: string }) {
 const router = useRouter(); const { showToast } = useToast(); const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false); const [values, setValues] = useState({ projectId: "", startsAt: "", endsAt: "", notes: "" });
 useEffect(() => { const openFromCalendar = () => setOpen(true); window.addEventListener("coolink:new-appointment", openFromCalendar); return () => window.removeEventListener("coolink:new-appointment", openFromCalendar); }, []);
 async function submit(e: FormEvent) { e.preventDefault(); setSaving(true); try { const res = await fetch("/api/admin/appointments", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(values) }); const data = await res.json(); if (!res.ok) throw new Error(data.error); showToast("Wizyta została zaplanowana."); setOpen(false); router.refresh(); } catch (err) { showToast(err instanceof Error ? err.message : "Nie udało się zaplanować wizyty.", "error"); } finally { setSaving(false); } }
 return <><button disabled={!projects.length} onClick={() => setOpen(true)} className="border border-ink-gold px-5 py-3 text-xs tracking-[0.08em] text-ink-gold hover:bg-ink-gold hover:text-ink-black disabled:opacity-40">{label}</button>{open && <AppModal title="Zaplanuj wizytę" subtitle="Wybierz projekt klienta i czas spotkania." onClose={saving ? () => undefined : () => setOpen(false)} closeOnBackdrop={!saving}><form onSubmit={submit} className="grid gap-4"><label className="flex flex-col gap-2 text-[11px] tracking-[0.1em] text-ink-grey">PROJEKT<select required value={values.projectId} onChange={(e) => setValues({ ...values, projectId: e.target.value })} className="border border-ink-white/20 bg-ink-black px-3 py-2.5 text-sm normal-case tracking-normal text-ink-white outline-none focus:border-ink-gold"><option value="">Wybierz projekt</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.client.firstName} {project.client.lastName} — {project.title}</option>)}</select></label><div className="grid gap-4 sm:grid-cols-2"><label className="flex flex-col gap-2 text-[11px] tracking-[0.1em] text-ink-grey">OD<input required type="datetime-local" value={values.startsAt} onChange={(e) => setValues({ ...values, startsAt: e.target.value })} className="border border-ink-white/20 bg-ink-black px-3 py-2.5 text-sm normal-case tracking-normal text-ink-white outline-none focus:border-ink-gold" /></label><label className="flex flex-col gap-2 text-[11px] tracking-[0.1em] text-ink-grey">DO<input required type="datetime-local" value={values.endsAt} onChange={(e) => setValues({ ...values, endsAt: e.target.value })} className="border border-ink-white/20 bg-ink-black px-3 py-2.5 text-sm normal-case tracking-normal text-ink-white outline-none focus:border-ink-gold" /></label></div><label className="flex flex-col gap-2 text-[11px] tracking-[0.1em] text-ink-grey">NOTATKA (OPCJONALNIE)<textarea value={values.notes} onChange={(e) => setValues({ ...values, notes: e.target.value })} rows={3} className="border border-ink-white/20 bg-transparent px-3 py-2.5 text-sm normal-case tracking-normal text-ink-white outline-none focus:border-ink-gold" /></label><div className="flex gap-3"><button disabled={saving} className="border border-ink-gold px-4 py-2.5 text-xs text-ink-gold disabled:opacity-50">{saving ? "ZAPISYWANIE…" : "ZAPLANUJ"}</button><button type="button" onClick={() => setOpen(false)} className="text-xs text-ink-grey hover:text-ink-white">Anuluj</button></div></form></AppModal>}</>;
}
