"use client";

import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { useToast } from "@/components/admin/ToastProvider";

export default function NewClientForm() {
  const router = useRouter(); const { showToast } = useToast();
  const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false);
  const [values, setValues] = useState({ firstName: "", lastName: "", email: "", phone: "", tags: "" });
  async function submit(e: FormEvent) { e.preventDefault(); setSaving(true); try { const res = await fetch("/api/admin/clients", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(values) }); const data = await res.json(); if (!res.ok) throw new Error(data.error); showToast("Klient dodany do CRM."); setOpen(false); setValues({ firstName: "", lastName: "", email: "", phone: "", tags: "" }); router.refresh(); } catch (error) { showToast(error instanceof Error ? error.message : "Nie udało się dodać klienta.", "error"); } finally { setSaving(false); } }
  if (!open) return <button type="button" onClick={() => setOpen(true)} className="border border-ink-gold px-5 py-3 text-[13px] font-medium tracking-[0.08em] text-ink-gold transition-colors hover:bg-ink-gold hover:text-ink-black">+ NOWY KLIENT</button>;
  return <form onSubmit={submit} className="grid w-full gap-3 border border-ink-white/15 bg-ink-charcoal/40 p-4 sm:grid-cols-2"><input required value={values.firstName} onChange={(e) => setValues({ ...values, firstName: e.target.value })} placeholder="Imię" className="border border-ink-white/20 bg-transparent px-3 py-2 text-sm text-ink-white outline-none focus:border-ink-gold" /><input required value={values.lastName} onChange={(e) => setValues({ ...values, lastName: e.target.value })} placeholder="Nazwisko" className="border border-ink-white/20 bg-transparent px-3 py-2 text-sm text-ink-white outline-none focus:border-ink-gold" /><input required type="email" value={values.email} onChange={(e) => setValues({ ...values, email: e.target.value })} placeholder="E-mail" className="border border-ink-white/20 bg-transparent px-3 py-2 text-sm text-ink-white outline-none focus:border-ink-gold" /><input value={values.phone} onChange={(e) => setValues({ ...values, phone: e.target.value })} placeholder="Telefon (opcjonalnie)" className="border border-ink-white/20 bg-transparent px-3 py-2 text-sm text-ink-white outline-none focus:border-ink-gold" /><input value={values.tags} onChange={(e) => setValues({ ...values, tags: e.target.value })} placeholder="Tagi, np. VIP, cover-up" className="border border-ink-white/20 bg-transparent px-3 py-2 text-sm text-ink-white outline-none focus:border-ink-gold sm:col-span-2" /><div className="flex gap-3 sm:col-span-2"><button disabled={saving} className="border border-ink-gold px-4 py-2 text-xs text-ink-gold disabled:opacity-50">{saving ? "DODAWANIE…" : "DODAJ KLIENTA"}</button><button type="button" onClick={() => setOpen(false)} className="text-xs text-ink-grey hover:text-ink-white">Anuluj</button></div></form>;
}
