"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { useToast } from "@/components/admin/ToastProvider";

const OPTIONS = [["inquiry", "Nowe zgłoszenie"], ["reviewing", "W trakcie analizy"], ["accepted", "Zaakceptowany"], ["scheduled", "Wizyta zaplanowana"], ["completed", "Zakończony"], ["cancelled", "Anulowany"]] as const;

export default function ProjectManager({ id, initialStatus, initialNotes, estimatedPrice, finalPrice }: { id: string; initialStatus: string; initialNotes: string | null; estimatedPrice: number | null; finalPrice: number | null }) {
 const router = useRouter(); const { showToast } = useToast(); const [status, setStatus] = useState(initialStatus); const [notes, setNotes] = useState(initialNotes ?? ""); const [estimate, setEstimate] = useState(estimatedPrice?.toString() ?? ""); const [final, setFinal] = useState(finalPrice?.toString() ?? ""); const [saving, setSaving] = useState(false);
 async function save() { setSaving(true); try { const res = await fetch(`/api/admin/projects/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status, internalNotes: notes, estimatedPrice: estimate, finalPrice: final }) }); const data = await res.json(); if (!res.ok) throw new Error(data.error); showToast("Projekt zaktualizowany."); router.refresh(); } catch (e) { showToast(e instanceof Error ? e.message : "Nie udało się zapisać.", "error"); } finally { setSaving(false); } }
 return <section className="border border-ink-white/15 bg-ink-charcoal/40 p-5"><p className="text-[11px] tracking-[0.14em] text-ink-gold">ZARZĄDZANIE PROJEKTEM</p><div className="mt-5 grid gap-4 sm:grid-cols-3"><label className="flex flex-col gap-2 text-[11px] tracking-[0.1em] text-ink-grey">STATUS<select value={status} onChange={(e) => setStatus(e.target.value)} className="border border-ink-white/20 bg-ink-black px-3 py-2.5 text-sm normal-case tracking-normal text-ink-white outline-none focus:border-ink-gold">{OPTIONS.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="flex flex-col gap-2 text-[11px] tracking-[0.1em] text-ink-grey">WYCENA (PLN)<input inputMode="numeric" value={estimate} onChange={(e) => setEstimate(e.target.value)} className="border border-ink-white/20 bg-transparent px-3 py-2.5 text-sm normal-case tracking-normal text-ink-white outline-none focus:border-ink-gold" /></label><label className="flex flex-col gap-2 text-[11px] tracking-[0.1em] text-ink-grey">CENA KOŃCOWA (PLN)<input inputMode="numeric" value={final} onChange={(e) => setFinal(e.target.value)} className="border border-ink-white/20 bg-transparent px-3 py-2.5 text-sm normal-case tracking-normal text-ink-white outline-none focus:border-ink-gold" /></label></div><label className="mt-4 flex flex-col gap-2 text-[11px] tracking-[0.1em] text-ink-grey">NOTATKI WEWNĘTRZNE<textarea value={notes} onChange={(e) => setNotes(e.target.value)} rows={5} className="border border-ink-white/20 bg-transparent px-3 py-2.5 text-sm normal-case tracking-normal text-ink-white outline-none focus:border-ink-gold" /></label><button type="button" onClick={save} disabled={saving} className="mt-5 border border-ink-gold px-4 py-2.5 text-xs tracking-[0.08em] text-ink-gold hover:bg-ink-gold hover:text-ink-black disabled:opacity-50">{saving ? "ZAPISYWANIE…" : "ZAPISZ ZMIANY"}</button></section>;
}
